server:
  port: 8300
spring:
  application:
    name: user-01
  datasource:
    name: aliyunDatasource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.98.115.245:3306/user?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123456  
eureka:
  instance:
    prefer-ip-address: true
    instance-id: user-01
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
mybatis:
  mapper-locations: classpath:/mapper/**/*xml
  type-aliases-package: com.example.user_common.mapper    
info:
  author: XXX
  build-version: 1  
management:
  endpoints:
    web:
      exposure:
        include: *
    health:
      show-details: always
    shutdown:
      enabled: true
